### ISSUE TITLE
Escape sequence \e

### ISSUE THREAD

**Issue by deven96** [nerdeveloper/stacks#10]
\e is for Linux
\x1B is for Mac
\033 is cross platform

I know this now because while writing a setup script for Mac, I got the escape characters back instead of properly formatted

**Comment by nerdeveloper** [comment]
I think i used the `\033`which I supposed is cross-platform. Is there any bug that needs to be fixed? if so, point me in the file, please.

**Comment by deven96** [comment]
> I think i used the `\033`which I supposed is cross-platform. Is there any bug that needs to be fixed? if so, point me in the file, please.

Yeah search for `\e[0m` in the codebase. The sequence that is supposed to escape back to normal mode. You will see all occurrences

**Comment by nerdeveloper** [comment]
wow, I see what you mean, I will check it out and replace. Thank you @deven96
